[env:freenove_s3_wroom]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; Freenove N16R8: 16MB Flash Quad, 8MB PSRAM Octal
; GPIO35-37 intern fuer PSRAM reserviert -> nie verwenden!
board_build.arduino.memory_type = qio_opi
board_build.partitions          = large_spiffs_16MB.csv

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCORE_DEBUG_LEVEL=0
  -DCONFIG_ESP32_WIFI_SW_COEXIST_ENABLE=1

lib_deps =
  adafruit/Adafruit ILI9341@^1.6.0
  adafruit/Adafruit GFX Library@^1.11.9
  https://github.com/max22-/ESP32-BLE-MIDI.git
  lathoub/AppleMIDI@^3.2.0
